# 4.5 Validate BST: Implement a function to check if a binary tree is a binary search tree
cc_binary(
	name="validate_bst_4_5",
	srcs=["validate_bst_4_5.cpp"],
	deps=["//lib/graph:graphs"],
)

# 4.6 successor: find the in-order successor of a node
cc_binary(
	name="successor_4_6",
	srcs =["successor_4_6.cpp"],
	deps=["//lib/graph:graphs"]
)
