# Todo convert in cc_test with gtest
cc_binary(
	name='graphs_test',
	srcs=['graphs_test.cpp'],
	deps=['//lib/graph:graphs'],
	copts=['-std=c++17'],
)

cc_binary(
	name='binary_tree',
	srcs=['binary_tree.cpp'],
	deps=['//lib/graph:graphs'],
)
